# Generated by Django 3.1.7 on 2021-03-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('store', '0002_store_manager_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.film')),
                ('store_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
        ),
    ]
