# Generated by Django 3.1.7 on 2021-03-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=240)),
                ('address2', models.TextField(max_length=240, null=True)),
                ('district', models.TextField(max_length=120)),
                ('postal_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=120)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=120)),
                ('last_name', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('active_bool', models.BooleanField(default=False)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateField(null=True)),
                ('active', models.SmallIntegerField()),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.address')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=120)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('county_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.country')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.city'),
        ),
    ]
