# Generated by Django 3.1.7 on 2021-03-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='county_id',
            new_name='country_id',
        ),
    ]
