# Generated by Django 3.1.7 on 2021-03-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
