# Generated by Django 3.1.7 on 2021-03-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_auto_20210303_1742'),
        ('customers', '0006_auto_20210303_1742'),
        ('store', '0005_auto_20210303_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('rental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.rental')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
