# Generated by Django 3.1.7 on 2021-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('staff', '0002_auto_20210303_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ManyToManyField(to='store.Store'),
        ),
    ]
