# Generated by Django 3.1.7 on 2021-03-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_manager_staff_id'),
        ('staff', '0003_auto_20210303_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
