# Generated by Django 3.1.7 on 2021-03-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210303_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
