# Generated by Django 3.1.7 on 2021-03-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_manager_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
