# Generated by Django 3.1.7 on 2021-03-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0002_auto_20210221_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_update', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('rental_duration', models.PositiveSmallIntegerField()),
                ('rental_rate', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('replacement_cost', models.PositiveIntegerField()),
                ('rating', models.CharField(max_length=120)),
                ('last_update', models.DateTimeField(null=True)),
                ('special_features', models.TextField()),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.category')),
                ('film_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.film')),
            ],
            options={
                'verbose_name_plural': 'Film Categories',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True)),
                ('actor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.actor')),
                ('film_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.language'),
        ),
        migrations.AddField(
            model_name='film',
            name='original_language_id',
            field=models.ForeignKey(db_column='original_language_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromlanguage', to='film.language'),
        ),
    ]
